### PR TITLE
RPM packaging via CPack

### LINKED ISSUE #238: Implement RPM packaging via `cpack`
...and use and remove all leftovers from the repo.

### PR DESCRIPTION
**Pull request by traceon**
Closes #238

### CODE REVIEW

**Comment by filimonov** [comment]
Can you upload somewhere the resulting spec file to review / rpm to test?

**Comment by filimonov** [comment]
BTW to build rpm some extra flag should be passed?

**Comment by traceon** [comment]
> BTW to build rpm some extra flag should be passed?

No, the same `cmake --build . --config RelWithDebInfo --target package` will work.

**Comment by traceon** [comment]
> Can you upload somewhere the resulting spec file to review / rpm to test?

Here is the generated specs file:
```
# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/clickhouse-odbc-1.1.8-Linux
Summary:        ClickHouse ODBC Driver (64-bit)
Name:           clickhouse-odbc
Version:        1.1.8
Release:        1%{?dist}
License:        ASL 2.0
Group:          Applications/Databases
Vendor:         Yandex LLC

Url: https://github.com/ClickHouse/clickhouse-odbc
Requires: unixODBC












Prefix: /usr/local





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS

%define _unpackaged_files_terminate_build 0


%define _binary_payload w9.gzdio

%description


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean

%post



%postun


%pre


%preun


%files
%defattr(-,root,root,-)
%dir "/usr/local"
%dir "/usr/local/lib64"
"/usr/local/lib64/libclickhouseodbc.so"
"/usr/local/lib64/libclickhouseodbcw.so"
%dir "/usr/local/share"
%dir "/usr/local/share/doc"
%dir "/usr/local/share/doc/clickhouse-odbc"
%dir "/usr/local/share/doc/clickhouse-odbc/config"
"/usr/local/share/doc/clickhouse-odbc/config/clickhouse-odbc.tdc.sample"
"/usr/local/share/doc/clickhouse-odbc/config/odbc.ini.sample"
"/usr/local/share/doc/clickhouse-odbc/config/odbcinst.ini.sample"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.1.8-1%{?dist}
  Generated by CPack RPM (no Changelog file were provided)


```

**Comment by filimonov** [comment]
Should we add to deps: openssl libicu libtool-ltdl
? 

Also spec from Vlad had this (not sure if needed) 
https://github.com/Altinity/clickhouse-odbc-rpm/blob/3eb2b5996074de45f347bdad6517de1971639ee0/src/clickhouse.spec.in#L88

**Comment by traceon** [comment]
> Should we add to deps: openssl libicu libtool-ltdl?

No, because the RPM builder detects such dependencies automatically, and this is very convenient, because we don't want to depend on them if we actually don't link with them dynamically.

**Comment by traceon** [comment]
> Also spec from Vlad had this (not sure if needed)
> https://github.com/Altinity/clickhouse-odbc-rpm/blob/3eb2b5996074de45f347bdad6517de1971639ee0/src/clickhouse.spec.in#L88

I don't think this is necessary, because ODBC drivers are loaded by ODBC driver manager code usually explicitly by `dlopen()`'ing them using absolute file path from `odbcinst.ini`.

**Comment by filimonov** [comment]
Found answers in https://docs.fedoraproject.org/en-US/packaging-guidelines/#_no_files_or_directories_under_srv_usrlocal_or_homeuser

**Comment by traceon** [comment]
> Found answers in https://docs.fedoraproject.org/en-US/packaging-guidelines/#_no_files_or_directories_under_srv_usrlocal_or_homeuser

What does this imply?

**Pull request merged**
