### PR TITLE
Tableau fixes

### PR DESCRIPTION
**Pull request by traceon**
Aiming at solving issues from:
https://github.com/ClickHouse/clickhouse-odbc/issues/210
https://github.com/ClickHouse/clickhouse-odbc/issues/176
..and some others.

### CODE REVIEW

**Comment by yurifal** [comment]
Please add the following customisation 
as it needs for the correct **Top N Filter** in Tableau:

`        <customization name='CAP_QUERY_SORT_BY_DEGREE' value='no' />
`

BTW, the version tag would be rather version='18.1' than '8.10'
though it doesn't make any difference in the wild.

**Comment by traceon** [comment]
> BTW, the version tag would be rather version='18.1' than '8.10'

I am choosing the lowest version that supports all of the mentioned capabilities.

**Comment by traceon** [comment]
@yurifal could you please try that TDC and share your thoughts on how it worked for you.
Please make sure you set the actual driver name (from your `odbcinst.ini`) in `<driver name='ClickHouse Driver' />` section and see **both** `...Found TDC...` and `...Found matching TDC...` lines in the Tableau log, as described in https://help.tableau.com/current/pro/desktop/en-us/odbc_customize.htm . Thanks!

**Comment by yurifal** [comment]
I've tried the TDC, and it works on both Windows and macOS -- 
but **only** with the version **1.1.1.20191108** of the ODBC driver. 

No luck with the latest version 1.1.2.20191216.
The errors are the same as reported previously (sic), 
and it looks like an unrelated issue which is specific 
to this version of the driver (latest as of now).

I've not tested with the recent commits, though.
Waiting for the release.

BTW, the correct tag for Windows is **<driver name='ClickHouseDriverW' />** 
that's how the driver name string is set by the Windows ODBC Manager 
(upon the driver installation i guess). On macOS it could / should be the same 
(for the sake of unity), ditto on the Tableau Server (both Windows and Linux).

**Comment by traceon** [comment]
@yurifal thanks. Since I still feel I don't have the full understanding of what is not working for you, could you please tell which version of tableau are you using, and exact steps that I need to take to see what you see.

**Comment by yurifal** [comment]
Please find the attached two screencasts for both versions 1.1.1.20191108 and 1.1.2.20191216.

v_1 1 1 20191108

v_1 1 2 20191216

You can contact me directly by the same nick (both Telegram and Skype) if you wish.

**Comment by yurifal** [comment]
Digging into it a bit further, it looks like the CH couldn't digest the code 
that Tableau is generating when applying the **IN/OUT Set conditions** on a view.
The simple Filter condition (for the IN Set Members) does work correctly, though.

My suggestion is to add the following Customization to the TDC file 
(to avoid the IN/OUT erratic behaviour in Tableau Desktop & Server altogether):

`<customization name='CAP_QUERY_INOUT_JOINS' value='no' />`

When (if) the state of affairs would be changed in the future versions of CH, 
this customization wouldn't be necessary, i guess.

**Comment by filimonov** [comment]
@yurifal can you also show the bad query sample generated by tableau? (to understand that exactly is not working properly, and maybe fix in further clickhouse versions)

**Comment by yurifal** [comment]
Here is the query Tableau sends to CH (using **ontime** dataset for example):

```
SELECT COALESCE(`ontime`.`Carrier`, '') AS `Calculation_1439885285864144896`,
    (CASE WHEN (NOT (`t0`.`XTableau_join_flag` IS NULL)) THEN 1 ELSE 0 END) AS `io_YF___Top_5_Carriers_by_Distance_nk`,
    SUM(CAST(`ontime`.`Distance` AS FLOAT)) AS `sum_Distance_ok`
  FROM `ontime`
    LEFT JOIN (
    SELECT TOP 5 MIN(1) AS `XTableau_join_flag`,
      SUM(CAST(`ontime`.`Distance` AS FLOAT)) AS `X__alias__0`,
      COALESCE(`ontime`.`Carrier`, '') AS `none_Calculation_1439885285864144896_nk`
    FROM `ontime`
    GROUP BY COALESCE(`ontime`.`Carrier`, '')
    ORDER BY SUM(CAST(`ontime`.`Distance` AS FLOAT)) DESC,
      COALESCE(`ontime`.`Carrier`, '') ASC
  ) `t0` ON (COALESCE(`ontime`.`Carrier`, '') = `t0`.`none_Calculation_1439885285864144896_nk`)
  GROUP BY COALESCE(`ontime`.`Carrier`, ''),
    (CASE WHEN (NOT (`t0`.`XTableau_join_flag` IS NULL)) THEN 1 ELSE 0 END);
```

Besides of coalescing the Carrier and casting the Distance 
the query aim to mark the Top 5 Carriers with 1 and others with 0 
in the auto-generated column io_YF___Top_5_Carriers_by_Distance_nk, 
which does not happen.

**Pull request merged**
